dist: trusty
sudo: required
services:
- docker
language: node_js
node_js:
- 9.5.0
branches:
  except:
  - /\+travis\.\d+$/
  - /^\d+\.\d+\.\d+-.*\d+$/
env:
  global:
  - ATOMIST_TEAM=T29E48P34
  - DOCKER_REGISTRY=atomist
  - DOCKER_USER=atomist
  - secure: wtoCbKE+6/FemUjjgQYbhJV8Z8Fh2bb9FLjQXtlKvF3ksMZQyWmHDLmHTl0nZtIfAlqyw78VYrgCHvqYtOsVCx7Hwg8BB30MCNLXNkP5LwP/Jz/gfPmvLk6tLOZmOWPnzUCi1+prSHJdy/AweqU/GWBQVceBxTGBb+eLF3UaThtz50SiK5qsRKDkQMAUVpeoQAtuLqR7WvI/F0QSd1jUk9ITy6ZC2+kmWgo3k0tbyVYCV06cb7ZD4QC3Yz0Vp1lj+9OGxQyNXoCqHGA0GmNh0B2YOFSrgoNBbRKw7iW+WG1USGgVCbg5zc6LNAMvpXaVhOj7pDbuI27e/xY/yne4pxdrmo4sPFPTqclNEBZGFWid8IckvicU7P8zJuudIog9hACESA9faZj/H/+KyvIXHL/zaP6ei5gyH9c5MidWHRzVDMRGXAZE9MsK+4ndvnj0cXiZ5w7q1IJLjfhktI9+vsue/P9rwVjMU+8//Xk+LoYdWyLy1hyjsFzDpZzU/iKl2w82SRVVYwlcFJeANw40Z/pcsV07Jr9dYmpa7Z7LKtvj1O3XW17UuYpzkmdwiQSRgh0xxbQqww/l5uNymbRxyMoyNhWXQq4Lwai/KjdRqkF0ufATieHXkNUmoVruyrApQyG68zWNLiruqmJCCxjc8MoCTHNxTAWLIPLicF/EIdU=
  - secure: fHSWdeFZuzf6ICNgEUxfOzmsLYp0dsEsJ3tkZjPcAkeIdxKiT1lSv36Q40Va9cnPJcFxqjYA1wWu+3V1QAd8+JODqSR79IkDuDqXZgTWVLe5+ETsQLcnwy/3He1imXdCp6JrrSMgWhxC/EpjiqIzBVBQjE12BCHjkTS8VGtVDKfng2q9I/9xEqe1LX5RN5JltIh2JhZTDyaSzLgrI3ky/JTv2azEDWzbg097ju2hMZxxRC+3TfXEpUqcBHO+4tMmO9gleeu28t9LS5PyUYOVFWzq+fdMti2W8E3m62FFxAfdUZJ2WMoJnkJKROt9hc4dgiQ/bAy81Ne6eCpwwIGIzLZM7101v6mLZ5P+rnCSYVRsTeZaHfPsxrEQnwK8N9hN1ZhXxR3LTkDTALwqGrCmYaTCFgfp5PTYzDkf8bnMbhIKOyq4f1bkwis/yDOLyr7ZfKsEPUHwCvmRl6p339JI8uj+5BOqXbkS9ATAQDy/UArTLXOFyH6nbV22WFCDSEcm4iXCPoI+x71MlruW7r8BgQF9ssBjUN/O1Zk1CZTIskzZitZpKkhfC9jimlckzcLoKqTS2VxBXef+gA4XnEbVWhcDSPrkMht7U4ITGcTXA2A1M4yi/b4Jf8+YjKuuvMYD55uVovMVgAQ4KHGcjYMI4PxKqLCXrSc6f5Zy7e8z3fs=
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
before_deploy:
- touch build/typedoc/.nojekyll
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/typedoc
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(m|rc)\.[0-9]+)?$
- provider: releases
  api_key: $GITHUB_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(m|rc)\.[0-9]+)?$
